### ISSUE TITLE
Research about the use of SQLite extensions to manage relationship between Models

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1047]
We could check if the relationships between models (TimeEntryModel -> Project -> Client) could be made at SQL level using this extension:
https://bitbucket.org/twincoders/sqlite-net-extensions

**Comment by monday8am** [comment]
@alfonsogarciacaro I have assigned this issue to you but we'll find a solution together. This issue is planned, not for the next week :)

**Comment by alfonsogarciacaro** [comment]
After having a look at the library, it seems to be a light version of EntityFramework. I personally don't like these abstraction layers as I'm already comfortable with SQL joins. Also, even if it makes a bit easier to work with databases from a OO language, there's still the cognitive load of learning how the library works instead of using a standard like SQL. Finally, I'm always wary of these ORM abstractions because they usually make you load too many records onto memory when querying the database.
Of course, this is only my opinion and if there's a clear advantage of using this library for team, I will be happy to implement it :)

**Comment by monday8am** [comment]
ok ok. Let's remove it from the scope. For a *real* ORM we could try *Realm* ;)
