### ISSUE TITLE
TestNewFutureStartChangeNoStop failing

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1119]
[This test](https://github.com/toggl/mobile/blob/master/Tests/Data/Models/TimeEntryModelTest.cs#L328-L329) is failing when run after 23:00 UTC (because adding one hour will increase the day component too. Apparently the problem is in the [`TimeEntryModel.StartTime` set](https://github.com/toggl/mobile/blob/master/Phoebe/Data/Models/TimeEntryModel.cs#L174-L177) but I'm not entirely sure what's the purpose of these lines so I don't know how to fix it properly. Please, @monday8am, have a look when you have time.

**Comment by monday8am** [comment]
good catch. I understand the idea: the .New state for time entries is an internal state and is used by only one entry in the DB. This time entry is used as a draft to create others (we could discuss advantages or not later, I can't find them). The test tries to ensure that changes of StartTime in a draft entry (not saved, not started) will set a random value to StopTime (it is null by default), seems to be the value is not really important.

Why the test uses the Utc.Now? because the random value given to StopTime uses it too. Why to the future? Because then the test enters inside the conditional and with Duration = 0 -> StartTime = StopTime.
https://github.com/toggl/mobile/blob/master/Phoebe/Data/Models/TimeEntryModel.cs#L179-L180

Solution: We don't make this kind of changes to a draft time entry and we're moving to another kind of approach (without this Draft time entry maybe). Just remove the test.

**Comment by alfonsogarciacaro** [comment]
Closed by [this PR](https://github.com/toggl/mobile/pull/1123)
