### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object at IsNetworkFailure method.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1155]
Raygun report https://app.raygun.io/crashreporting/gn9q04/errors/1026926495 has more details about the error

**Comment by alfonsogarciacaro** [comment]
It seems this problem is caused because `ExceptionExtensions.IsNetworkFailure` is called with a null argument. As in most cases, this method is called in catch clauses the exception shouldn't be null. However, in `LogTimeEntriesListFragment.SyncFinished` this method is called on `msg.FatalError` which could be null. In any case, I've modified `ExceptionExtensions.TraverseTree` so there's also a null check before returning anything and added a unit test just in case.
