### ISSUE TITLE
Time entry durations are shown modulo 24 hours

### ISSUE THREAD

**Issue by amulware** [toggl/mobile#1537]
Encountered this when changing the end-DATE of a time entry to the next day. The total hours of the day updated correctly, but the entry itself displayed ~1hour as it was before, even though it should have been 25 hours.

Not sure if this should be possible from a usability standpoint at all (selecting end date), or how longer than 24h entries should be handled.

Observed on Android, may be on iOS as well.

**Comment by alfonsogarciacaro** [comment]
I saw something like that too but it fixed itself after restarting the app. If it's the same for you probably it has to do with the refreshing of the view.

**Comment by amulware** [comment]
Restarting the app does not help for me. It continues showing the entry duration mod 24h in the list.

**Comment by alfonsogarciacaro** [comment]
First attempt to fix this in [this commit](https://github.com/toggl/mobile/commit/37c1ebacdd2e837be79e7fe8ac50070f2f006873).

Two problems identified:
1- The string formatting was implicitly calling `TimeSpan.Hours` instead of `TotalHours`. That's what the commit solves.
2- In `unidirectional`, `TimeEntryData.GetFormattedDuration` is being called with the first parameter (`UserData`) set to null. We need to decide a new strategy to access `UserData` at this point. For now, the commit is using the classic format as the default option.

Besides the Timer view, this problems also affects (though differently) the TE Edit view. For some reason the format used there is different from the Timer (see [here](https://github.com/toggl/mobile/blob/unidirectional/Phoebe/ViewModels/EditTimeEntryVM.cs#L86-L87)). We should decide if we want to unify this.

**Comment by monday8am** [comment]
closed by #1541
