### ISSUE TITLE
iOS No posibility to login with Google account

### ISSUE THREAD

**Issue by ovidiur** [toggl/mobile#1821]
I've created a toggl account on web by loging in with my Google account. After installing the iOS app, there's no option to login with my Google account, esentially locking me out.

![img_1222](https://cloud.githubusercontent.com/assets/3442410/18176168/2bea0f50-707d-11e6-8e0f-8f610029a7cd.jpg)

Additionally, I have no idea how to transition to a toggl account; web  settings section only gives me the posibility to change my password, but it's asking for my old password. What old password?

**Comment by amulware** [comment]
Hey @ovidiur,

We had to disable google login in our recent update because of technical reasons. We hope it will be back with one of the next updates.

In the meantime, you can get yourself a password by entering your google email address in the password-reset form here: https://toggl.com/forgot-password
You can then log in with that password in the mobile app.

Sorry for the inconvenience!
