### ISSUE TITLE
use hex_color for project color (returned by reports API)

### ISSUE THREAD

**Issue by refiito** [toggl/mobile#533]
old color field will be deprecated and phased out (with the coming on main API v9)

**Comment by monday8am** [comment]
@refiito which is the state of this? Could we already use the API v9?

**Comment by pe0ny** [comment]
Because of the contrast issue, we need to update projects list view and edit TE view accordingly:
display coloured circle (project colour) and project name (12% darker) next to it.

![toggl ios - projects without search bar 1x](https://cloud.githubusercontent.com/assets/5064445/20139723/29c8adb4-a690-11e6-949e-7dcfbccf7258.png)

Additional info is available in zeplin (including tasks). Since project search #1702 is not implemented yet, ignore the search bar.

Same layout: circle + project name applies to edit view as well.
