### ISSUE TITLE
Edit TE: remove tag's color

### ISSUE THREAD

**Issue by masterrr** [toggl/mobile#629]

**Comment by masterrr** [comment]
@monday8am what colors are to be removed? Edit TE screen?
![screenshot_2015-04-29-18-22-46](https://cloud.githubusercontent.com/assets/720966/7394585/2c7bc44e-ee9d-11e4-841c-252251d7efd6.png)

**Comment by monday8am** [comment]
@pe0ny My question here is the follow: we're editing a Time Entry that includes a project ( and a color). We're not showing this color in any place, maybe a solution could be fill out the background of client banner with the project color:

![screen shot 2015-04-29 at 18 30 47](https://cloud.githubusercontent.com/assets/1842773/7396024/2e223b7e-ee9e-11e4-9254-ec40365fb821.png)

In any case, if we include the color of project in this screen, still we'll have the color of tags and maybe is a bit confused.

**Comment by pe0ny** [comment]
We shouldn't definitely fill the client tag with project color. Then it'll be like super confusing because clients don't have colors (only projects do). That's why I decided to color client tag grey to be as neutral as possible.
We'll display colors on home screen (TE list) to let users know and associate time entries and projects. So I think we don't need to display project color in edit view (besides you can't change color there)

**Comment by pe0ny** [comment]
ps: tags should have 2px border radius (rounded corners). I think screenshots above have bigger radius atm.

**Comment by monday8am** [comment]
@pe0ny got it. Thanks ( @masterrr )

**Comment by masterrr** [comment]
I think rounded corners was only one thing to fix. Must close now @monday8am ?

**Comment by masterrr** [comment]
Closed by https://github.com/toggl/mobile/pull/663
