### ISSUE TITLE
Align of UI elements.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#631]
@pe0ny: is the align correct in this snapshots (not in my opinion)? In case of not, let me know what is the correct solution.

![nexus 4 kitkat screentshot 1](https://cloud.githubusercontent.com/assets/1842773/7374219/3fad26f6-edd1-11e4-9d99-825aa9d741e6.png)

![nexus 4 kitkat screentshot 3](https://cloud.githubusercontent.com/assets/1842773/7374224/49bd2d8a-edd1-11e4-8f6e-91a7c9c28297.png)

![nexus 4 kitkat screentshot 2](https://cloud.githubusercontent.com/assets/1842773/7374222/43d649ba-edd1-11e4-93e7-3bda3fb6537b.png)

**Comment by pe0ny** [comment]
Keylines for TE list:
![keylines-1](https://cloud.githubusercontent.com/assets/5064445/7387372/74a0b796-ee54-11e4-829d-ada24b60e290.png)

Some notes:
* Menu should be aligned left (like we have atm)
* "Today", "Yesterday" etc - 16dp from left
* TE text - 32dp from left

Edit view:
* 32dp horizontal margins (from the left and right edges)

**Comment by monday8am** [comment]
Nice! thanks @pe0ny 
There is one element missing: the total time per day, at right inside day session header. The alignment of this element is at 16dp from right?

**Comment by pe0ny** [comment]
Sorry. But yes, 16dp from right.

**Comment by monday8am** [comment]
:+1:

**Comment by pe0ny** [comment]
Can we change projects list similar to material design?
![toggl-android-projects](https://cloud.githubusercontent.com/assets/5064445/7585616/389f454c-f8ad-11e4-997a-ad5ba0b9bd91.png)

Without all the extra functionality of course but android shouldn't look like iOS:
* remove backgrounds (project list should look like similar to TE list)
* add color indicators + colored text

**Comment by monday8am** [comment]
:) we think exactly in the opposite way:

> android shouldn't look like iOS

I don't understand why not. There are different systems but design solutions (organisation, colours, content) works in the same way. 

> project list should look like similar to TE list

My personal opinion is that is an inconvenient related with usability. Different elements should look slightly different, if not, lead to confusion. We have 3 types of cells, 2 of them are TE cells and the other one is a project cell and we'll have more cell types ( clients, tags?). We should use a common layout to TE cells maybe.

I tested with the background color to see reactions, if you don't like I'll back to original design. Please, let me know what you think about my comments.

**Comment by pe0ny** [comment]
I'm not saying that android can't look like iOS (imo I like to mix material with ios a bit) but we decided to use Material Design and this specific view we are talking about (projects list) doesn't match with other design atm. That's the problem.

I also agree that different elements should look slightly different but consistency is the most important. And that's what we should apply for. That's why we should use similar listing. Like we display time entries - white blocks and small color indicator on the left - we should continue with the same style.

Let's change it back (similar to TE list like the example above). Only difference from the TE list is that blocks are 56dp height not 72dp.

**Comment by taavirehemagi** [comment]
Alright, I'll change it back then.

**Comment by taavirehemagi** [comment]
closed by #671
