### ISSUE TITLE
Task button to display task list.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#788]
@pe0ny we need a suggestion for the task button. Currently if you select a project that contains tasks, the tasks are displayed but you're not able to select only the project. A solution could be:

1. If you press the whole item you only pick the project.
2. If you press the task button then the task list is displayed. Currently the word task don't looks like a button (of course). This button will change the state if tasks are displayed with an arrow or something like this.
3. If you press a task, you pick the project with the corresponding task.
4. The task item is not easy to distinguish from project item. Maybe we should use different background color or margin?

![screen shot 2015-06-16 at 16 41 12](https://cloud.githubusercontent.com/assets/1842773/8185986/c11137fe-1447-11e5-8da8-351450b0683f.png)

**Comment by pe0ny** [comment]
In this case I would suggest to use icon instead of button. The flow you described is correct:

1. If you press the whole item, only the project will be selected.
2. If you press "Task" then task list will be displayed. Icon will change to an arrow after that.
3. If you press a task, project with current task will be selected.
4. I believe if we use icon instead of a button, it will be more prominent.

![projects](https://cloud.githubusercontent.com/assets/5064445/8201530/bae8b17a-14da-11e5-9d5c-e4eb0168eaf8.png)
![projects-tasks](https://cloud.githubusercontent.com/assets/5064445/8201534/c4e07140-14da-11e5-9e59-c3c394c7c213.png)

**Comment by masterrr** [comment]
@pe0ny great! One question: what do three dots stand for? We don't have any options on projects _yet_?  Can we skip it and put the icon only?

**Comment by pe0ny** [comment]
Yes, atm you can skip it and use only task icon.
Three dots icon (more) is for "Add task", "Edit", and "Archive":

![projects-more](https://cloud.githubusercontent.com/assets/5064445/8201863/7fc4e728-14dd-11e5-8a5a-736413d4fd3b.png)

**Comment by masterrr** [comment]
@pe0ny great, thanks!
